version: '3'

services:
  webserver:
    image: php:8-apache
    network_mode: bridge
    expose:
      - 80
    environment:
      VIRTUAL_HOST: php.localhost
    volumes:
      - $PWD/html:/var/www/html
